---

# This uses a variable as this changes per distribution.

- name: "Ensure nginx is installed."
  become: true
  package:
    name: "{{ nginx_package_name }}"
    state: "{{ state | default('present') }}"
    use: apt