---
- name: Converge
  hosts: all
  gather_facts: yes
  tasks:
    - name: Testing role
      include_role:
        name: ansible-role-nginx

    # - name: Qualify balancing
    #   become: true
    #   copy:
    #     src: index.html
    #     dest: /var/www/html/
    #     owner: "{{ nginx_user }}"
    #     group: "{{ root_group }}"
    #     mode: 0640
    #   notify: restart nginx
